name: photo_editor
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-85.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  built_value: ^8.1.4
  built_collection: ^5.1.1
  http: ^0.13.4
  redux: ^5.0.0
  flutter_redux: ^0.9.0
  redux_epics: ^0.15.1
  freezed_annotation: ^1.1.0
  firebase_auth: ^3.3.12
  cloud_firestore: ^3.1.11
  firebase_storage: ^10.2.10

  image_picker: ^0.8.4+11
  image_editor: ^1.0.2
  extended_image: ^6.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  built_value_generator: ^8.1.4
  freezed: ^1.1.1
  flutter_lints: ^1.0.4

dependency_overrides:
  rxdart: ^0.27.3
  meta: ^1.7.0
  analyzer: ^3.4.1

flutter:

  uses-material-design: true

